// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using UnityStandardAssets;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;

namespace RMX
{


	public interface IGameController : ISingleton {
		void PauseGame(bool pause);
		void PauseGame (bool pause, object args);
	}
	public interface ISettings : ISingleton {
		bool PrintToScreen { get; set; }
		TextAsset Database { get; }
		bool IsDebugging(string feature);
		float MaxDisplayTime { get;}
	}

	public interface ISingleton {
		string name { get; }
//		ISingleton Singleton { get; set; }
		bool Destroyed { get; }
		GameObject gameObject { get; }
	}

	public static class Singletons {

		static bool _GC_Initialized = false;
		public static bool GameControllerInitialized {
			get {
				return _GC_Initialized;
			}
		}
		static bool _SettingsInitialized = false;
		public static bool SettingsInitialized {
			get {
				return _SettingsInitialized;
			}
		}

		static IGameController _gameController;
	 	public static IGameController GameController {
			get{ 
				return _gameController;
			}
		}
		static ISettings _settings;
		public static ISettings Settings {
			get {
				return _settings;
			}
		}


		public abstract class ASingleton<T> : RMXObject, ISingleton, EventListener
		where T : RMXObject, EventListener, ISingleton 
		{

			private static T _singleton = null;

			private static bool _isInitialized = false;


			protected virtual bool SetupComplete {
				get{ 
					return true;
				}
			}

			public static bool IsInitialized {
				get {
					return _isInitialized && (_singleton as ASingleton<T>).SetupComplete;
				}
			}



			protected virtual IGameController gameController { 
				get {
					return Singletons.GameController;
				}
			}
	//		{
	//			get {
	//				return (IGameController as ASingleton<T>).current;
	//			}
	//		}

	//		protected GameData gameData {
	//			get {
	//				return GameData.current;
	//			}
	//		}
	//
	//		protected GameCenter gameCenter {
	//			get {
	//				return GameCenter.current;
	//			}
	//		}

			protected virtual ISettings settings {
				get {
					return settings;
				}
			}
	//		{
	//			get {
	//				return (ISettings as ASingleton<T>).current;
	//			}
	//		}

			public static T current {
				get {
					if (IsInitialized) {
						return _singleton as T;
					} else {
						return Initialize() as T;
					}
				}
			}

			const string tempName = "324329hrNhfeuwh9";
			private bool _destroyed = false;
			public bool Destroyed {
				get {
					return _destroyed;
				}
			}




			public static T Initialize() {
				if (IsInitialized) 
					return _singleton;
				else {// if (ReadyToInitialize<T>()) {
					var aSingleton = new GameObject (tempName).AddComponent<T> ();
					if ((aSingleton as ISingleton).Destroyed) {
						return null;
					}
					aSingleton.gameObject.name = aSingleton.GetType ().Name;
	//				aSingleton.name = aSingleton.gameObject.name;
					if (!(aSingleton is IGameController) && Singletons.GameControllerInitialized) {
						var parent = Singletons.GameController.gameObject;
						aSingleton.gameObject.transform.SetParent (parent.transform);
					}
	//				if ((aSingleton as ASingleton<T>).AddToGlobalListeners) {
	//					Notifications.AddListener(aSingleton);
	//				}
					return aSingleton;
				} 
			}

			/// <summary>
			/// Gets a value indicating whether this <see cref="RMX.ASingleton`1"/> add to global listeners.
			/// </summary>
			/// <value><c>true</c> if add to global listeners; otherwise, <c>false</c>.</value>
			private bool AddToGlobalListeners { 
				get {
					System.Type classType = typeof(T);
					foreach (string vMethod in ListenerMethods) {
						MethodInfo method = classType.GetMethod (vMethod);
						if (method.DeclaringType != typeof(RMXObject)) 
							return true;
					}
					return false;
				}
			}

			private void warining() {
				if (!(_SettingsInitialized))
					Debug.LogWarning ("Setting not initialized before debugger");
			}

			private void MainInitCheck() {
				if (this is IGameController) {
					Singletons._gameController = this as IGameController;
					_GC_Initialized = true;
				} else if (this is ISettings) {
						Singletons._settings = this as ISettings;
					_SettingsInitialized = true;
				} 
			}

			/// <summary>
			/// Checks whether a singleton already exists. If so, object is destroyed.
			/// Otherwise it checks whether the EventListener methods have been overriden. If so, the object is added to the global EventListeners.
			/// </summary>
			protected void Awake() {
				var message = "__new__ <color=lightblue>" + this.GetType().Name + "</color>()";
				if (_singleton == null) {
					DontDestroyOnLoad (gameObject);
					_singleton = this as T;// as T;
					if (AddToGlobalListeners)
						Notifications.AddListener(this);
					MainInitCheck();
				} 
				else if (_singleton != this) {
					if (gameObject.name == tempName) {// gameObject.name == this.GetType().Name &&
						message += " -- <color=red> DELETING REDUNDANT " + this.GetType().Name + "</color>()";
						_destroyed = true;
						Destroy (gameObject);
						Destroy (this);
					} else {
						message += " -- <color=orange> DELETING REDUNDANT ASingleton: </color> " + this.GetType().Name + "</color>()";
						_destroyed = true;
						Destroy(this);
					}
				}
				if (Bugger.WillLog(Testing.Singletons, message))
					Debug.Log (Bugger.Last);

				_isInitialized = true;
			}

		}
	}
}

